// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using simplyBooksBE.Data;

#nullable disable

namespace simplyBooksBE.Migrations
{
    [DbContext(typeof(simplyBooksBEDbContext))]
    partial class simplyBooksBEDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("simplyBooksBE.Models.Authors", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            ID = 101,
                            Email = "alice.johnson@email.com",
                            Favorite = true,
                            First_Name = "Alice",
                            ImageUrl = "https://randomuser.me/api/portraits/women/71.jpg",
                            Last_Name = "Johnson",
                            Uid = "A1"
                        },
                        new
                        {
                            ID = 102,
                            Email = "benjiman.lee@email.com",
                            Favorite = false,
                            First_Name = "Benjamin",
                            ImageUrl = "https://randomuser.me/api/portraits/men/74.jpg",
                            Last_Name = "Lee",
                            Uid = "A2"
                        },
                        new
                        {
                            ID = 103,
                            Email = "carla.martinez@email.com",
                            Favorite = true,
                            First_Name = "Carla",
                            ImageUrl = "https://randomuser.me/api/portraits/women/8.jpg",
                            Last_Name = "Martinez",
                            Uid = "A3"
                        },
                        new
                        {
                            ID = 104,
                            Email = "david.roberts@email.com",
                            Favorite = false,
                            First_Name = "David",
                            ImageUrl = "https://randomuser.me/api/portraits/men/54.jpg",
                            Last_Name = "Roberts",
                            Uid = "A4"
                        },
                        new
                        {
                            ID = 105,
                            Email = "emma.zhang@email.com",
                            Favorite = true,
                            First_Name = "Emma",
                            ImageUrl = "https://randomuser.me/api/portraits/women/35.jpg",
                            Last_Name = "Zhang",
                            Uid = "A5"
                        });
                });

            modelBuilder.Entity("simplyBooksBE.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Author_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<bool>("Sale")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Author_Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Author_Id = 101,
                            Description = "The Secret is a best-selling 2006 self-help book by Rhonda Byrne, based on the earlier film of the same name. It is based on the belief of the law of attraction, which claims that thoughts can change a person's life directly.",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51aOZmIj8LL._SX331_BO1,204,203,200_.jpg",
                            Price = 10,
                            Sale = true,
                            Title = "The Secret",
                            Uid = "B1"
                        },
                        new
                        {
                            Id = 202,
                            Author_Id = 102,
                            Description = "The Alchemist is a novel by Brazilian author Paulo Coelho that was first published in 1988. Originally written in Portuguese, it became a widely translated international bestseller.",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51aOZmIj8LL._SX331_BO1,204,203,200_.jpg",
                            Price = 15,
                            Sale = false,
                            Title = "The Alchemist",
                            Uid = "B2"
                        },
                        new
                        {
                            Id = 203,
                            Author_Id = 103,
                            Description = "The Power of Now: A Guide to Spiritual Enlightenment is a book by Eckhart Tolle. The book is intended to be a guide for day-to-day living and stresses the importance of living in the present moment and transcending thoughts of the past or future.",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51aOZmIj8LL._SX331_BO1,204,203,200_.jpg",
                            Price = 12,
                            Sale = true,
                            Title = "The Power of Now",
                            Uid = "B3"
                        },
                        new
                        {
                            Id = 204,
                            Author_Id = 104,
                            Description = "The 7 Habits of Highly Effective People, first published in 1989, is a business and self help book",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51aOZmIj8LL._SX331_BO1,204,203,200_.jpg",
                            Price = 20,
                            Sale = false,
                            Title = "The 7 Habits of Highly Effective People",
                            Uid = "B4"
                        },
                        new
                        {
                            Id = 205,
                            Author_Id = 105,
                            Description = "The Four Agreements: A Practical Guide to Personal Freedom is a self-help book by bestselling author Don Miguel Ruiz with Janet Mills. The book offers a code of personal conduct based on ancient Toltec wisdom that advocates freedom from self-limiting beliefs that may cause suffering and limitation in a person's life.",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51aOZmIj8LL._SX331_BO1,204,203,200_.jpg",
                            Price = 18,
                            Sale = true,
                            Title = "The Four Agreements",
                            Uid = "B5"
                        });
                });

            modelBuilder.Entity("simplyBooksBE.Models.Books", b =>
                {
                    b.HasOne("simplyBooksBE.Models.Authors", "Author")
                        .WithMany("Book")
                        .HasForeignKey("Author_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("simplyBooksBE.Models.Authors", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
